#pragma once

#include "vector/vector_helper.hpp"
#include "vector/ctor_test.hpp"
#include "vector/popback_test.hpp"
#include "vector/pushback_test.hpp"
#include "vector/capacity_test.hpp"
#include "vector/resize_test.hpp"
#include "vector/element_access_test.hpp"
#include "vector/clear_test.hpp"
#include "vector/swap_test.hpp"
#include "vector/relational_operators_test.hpp"
#include "vector/erase_test.hpp"
#include "vector/assign_test.hpp"
#include "vector/insert_test.hpp"
